<style>
	.footer {
        width: 100%;
        padding: 40px 0px;
        color: #ffffff;
        background-image: linear-gradient(to bottom right, #57998b, #345874);
        }

	.footer .container {
		padding-top: 0px;
	}

    .ft-list {
        column-count: 2;
        list-style-type: none;
        width: 420px;
    }

    .ft-list li {
        padding-bottom: 10px;
    }

    .ft-list a {
        color: #ffffff;
        text-decoration: none;
    }

    .ft-list a:hover {
        color: #ffffff;
        text-decoration: underline;
        text-underline-offset: 5px;
    }

    .ft-logos {
    	width: 224px;
    	margin-bottom: 25px;
    }
</style>

<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4 order-md-2">
        <div class="ft-logos d-flex justify-content-end">
          <a href="https://i.postimg.cc/90pYKyWC/HYPERMACHINE.png" class="me-3">
            <img src="https://i.postimg.cc/yxv5ZvfS/HYPERMACHINE-white.png" alt="HM" width="40" height="40">
          </a>
          <a href="https://www.pokemon.com/" class="me-3">
            <img src="img/ft_pkmnco.webp" alt="The Pokemon Company" width="110" height="12">
          </a>
          <a href="https://www.nianticlabs.com/">
            <img src="img/ft_niantic.webp" alt="Niantic Labs" width="50" height="61">
          </a>
        </div>
      </div>
      <div class="col order-md-1">
        <ul class="ft-list">
          <li>
            <a href="https://pokemongolive.com/">Pokémon GO Live</a>
          </li>
          <li>
            <a href="https://pokemongolive.com/leaderboard?hl=en">Leaderboard</a>
          </li>
          <li>
            <a href="https://pokemongolive.com/events/">Events</a>
          </li>
          <li>
            <a href="https://pokemongolive.com/news?hl=en">News</a>
          </li>
          <li>
            <a href="https://niantic.helpshift.com/hc/en/6-pokemon-go/?p=web&l=en">Support</a>
          </li>
          <li>
            <a href="https://rewards.nianticlabs.com/app/pokemongo/signin">Offer Redemption</a>
          </li>
          <li>
            <a href="https://pokemongolive.com/community-day/map?hl=en">Community Day Map</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
	

</body>
</html>